import Sutando from './src/index.js';

const {
  sutando,
  Paginator,
  Collection,
  Model,
  Pivot,
  Builder,
  Attribute,
  CastsAttributes,
  Migration,
  Scope,
  SoftDeletes,
  HasUniqueIds,
  now,
  getRelationName,
  getScopeName,
  getRelationMethod,
  getScopeMethod,
  getAttrMethod,
  getGetterMethod,
  getSetterMethod,
  getAttrName,
  compose,
  tap,
  ModelNotFoundError,
  RelationNotFoundError,
  InvalidArgumentError,
} = Sutando;

export {
  sutando,
  Paginator,
  Collection,
  Model,
  Pivot,
  Builder,
  Attribute,
  CastsAttributes,
  Migration,
  Scope,
  SoftDeletes,
  HasUniqueIds,
  now,
  getRelationName,
  getScopeName,
  getRelationMethod,
  getScopeMethod,
  getAttrMethod,
  getGetterMethod,
  getSetterMethod,
  getAttrName,
  compose,
  tap,
  ModelNotFoundError,
  RelationNotFoundError,
  InvalidArgumentError,
};
